FIND_PATH(XTRACT_INCLUDE_DIR NAMES xtract/libxtract.h)
# Look for the library.
FIND_LIBRARY(XTRACT_LIBRARY NAMES xtract)
# Handle the QUIETLY and REQUIRED arguments and set XTRACT_FOUND to TRUE if all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(XTRACT DEFAULT_MSG XTRACT_LIBRARY XTRACT_INCLUDE_DIR)



# Copy the results to the output variables.
IF(XTRACT_FOUND)
	SET(XTRACT_LIBRARIES ${XTRACT_LIBRARY})
	SET(XTRACT_INCLUDE_DIRS ${XTRACT_INCLUDE_DIR})
ELSE(XTRACT_FOUND)
	SET(XTRACT_LIBRARIES)
	SET(XTRACT_INCLUDE_DIRS)
ENDIF(XTRACT_FOUND)

MARK_AS_ADVANCED(XTRACT_INCLUDE_DIRS XTRACT_LIBRARIES)
